import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "@/lib/i18n";
import { LoadingProvider } from "@/lib/loading";
import { WorkExpandProvider } from "@/components/work/WorkExpandContext";
import { client } from "@/lib/sanity";
import { projectsQuery, type ProjectData } from "@/lib/queries";
import SiteChrome from "@/components/SiteChrome";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // The expand overlay is mounted here, so it needs the projects too — it has to
  // rebuild a case study by slug on history navigation, without the slider.
  let projects: ProjectData[] = [];
  try {
    projects = await client.fetch<ProjectData[]>(projectsQuery, {}, { next: { revalidate: 60 } });
  } catch {
    // Sanity unavailable — the slider renders the white card alone
  }

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${inter.variable} antialiased`}
      >
        <SiteChrome />
        <I18nProvider>
          <LoadingProvider>
            <WorkExpandProvider projects={projects}>
              {children}
            </WorkExpandProvider>
          </LoadingProvider>
        </I18nProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
